### ISSUE TITLE
No module named 'lino_secrets'

### ISSUE THREAD

**Issue by nkoech** [liqtags/DexScreenerClient#2]
On running the script the follow `ModuleNotFoundError` is raised:

```
Traceback (most recent call last):
  File "/home/test/DexScreenerClient/DexScreenerClient.py", line 1, in <module>
    from consts import trending_pairs_string_slugged, top_gaining_pairs_string_slugged, newest_pairs_string_slugged
  File "/home/test/DexScreenerClient/consts.py", line 1, in <module>
    from lino_secrets import SUPABASE_URL, SUPABASE_KEY, WS_TRENDING, WS_GAINERS, WS_NEWEST
ModuleNotFoundError: No module named 'lino_secrets'
```

**Comment by liqtags** [comment]
They are my own websocket nodes and keys. create your own secrets file or read the README about premium version.
