### ISSUE TITLE
Cannot import name 'WS_NEWEST'

### ISSUE THREAD

**Issue by nkoech** [liqtags/DexScreenerClient#3]
```
Traceback (most recent call last):
  File "/home/test/DexScreenerClient/DexScreenerClient.py", line 5, in <module>
    from get_newest_pairs import get_newest_pairs
  File "/home/test/DexScreenerClient/get_newest_pairs.py", line 1, in <module>
    from consts import WS_NEWEST
ImportError: cannot import name 'WS_NEWEST' from 'consts' (/home/test/DexScreenerClient/consts.py)
```

**Comment by liqtags** [comment]
They are my own websocket nodes and keys. create your own secrets file or read the README about premium version.
